### ISSUE TITLE
Unexpected info response: 400 when trying to login

### ISSUE THREAD

**Issue by Hairo** [codelv/protonmail#5]
Getting this error when trying to login, interestingly it was working as intended 2 days ago (oct 16th), maybe something changed in the API?

```INFO:twisted:Log opened.
INFO:twisted:Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f84b81836a8>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f84b81bff60>)
Traceback (most recent call last):
  File "./stats.py", line 99, in <module>
    enviar_email(ftext)
  File "./stats.py", line 32, in enviar_email
    client.api.login("[redacted]")
  File "/usr/local/lib/python3.5/dist-packages/protonmail/client.py", line 629, in login
    return run_sync(self._login, password, unlock, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/protonmail/clients/tx.py", line 34, in run_sync
    return crochet.run_in_reactor(wrapped)().wait(timeout)
  File "/home/hairo/.local/lib/python3.5/site-packages/crochet/_eventloop.py", line 241, in wait
    result.raiseException()
  File "/home/hairo/.local/lib/python3.5/site-packages/twisted/python/failure.py", line 467, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/hairo/.local/lib/python3.5/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python3.5/dist-packages/protonmail/client.py", line 649, in _login
    raise LoginError("Unexpected info response: {}".format(r.code))
protonmail.client.LoginError: Unexpected info response: 400
INFO:twisted:Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f84b81836a8>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f84b81bff60>)
INFO:twisted:Main loop terminated.

**Comment by frmdstryr** [comment]
Thanks for the report. Updated to support the api changes. Should be working again now.

**Comment by Hairo** [comment]
Thanks, working fine now.
