### ISSUE TITLE
5003 - Update required: Please refresh the page to load the latest version of the application

### ISSUE THREAD

**Issue by RandomStrangerOnTheInternet** [codelv/protonmail#8]
When attempting to login using the following snippet I receive the update required error.

```
from protonmail.client import Client

client = Client(Username='...', blocking=True)
client.api.login(password='...', timeout=60)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/development/protonmail-master/protonmail/client.py", line 671, in login
    return run_sync(self._login, password, unlock, timeout=timeout)
  File "/home/development/protonmail-master/protonmail/clients/tx.py", line 34, in run_sync
    return crochet.run_in_reactor(wrapped)().wait(timeout)
  File "/home/development/.local/lib/python3.6/site-packages/crochet/_eventloop.py", line 241, in wait
    result.raiseException()
  File "/home/development/.local/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/development/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/development/protonmail-master/protonmail/client.py", line 696, in _login
    "{} - {}".format(r.code, data))
protonmail.client.LoginError: Unexpected info response: 422 - {'Code': 5003, 'Error': 'Update required: Please refresh the page to load the latest version of the application', 'ErrorDescription': '', 'Details': {}}
```

**Comment by RandomStrangerOnTheInternet** [comment]
I have updated the `AppVersion` to `Web_3.16.2`, the client secret has remained the same `4957cc9a2e0a2a49d02475c9d013478d`

```
INFO:twisted:Log opened.
INFO:twisted:Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f71b8af0400>, <twisted.internet.endpoints._WrapperEndpoint object at 0x7f71b8af17b8>)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/development/protonmail-master/protonmail/client.py", line 671, in login
    return run_sync(self._login, password, unlock, timeout=timeout)
  File "/home/development/protonmail-master/protonmail/clients/tx.py", line 34, in run_sync
    return crochet.run_in_reactor(wrapped)().wait(timeout)
  File "/home/development/.local/lib/python3.6/site-packages/crochet/_eventloop.py", line 241, in wait
    result.raiseException()
  File "/home/development/.local/lib/python3.6/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/development/.local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/development/protonmail-master/protonmail/client.py", line 696, in _login
    "{} - {}".format(r.code, data))
protonmail.client.LoginError: Unexpected info response: 400 - {'Code': 10050, 'Error': 'Invalid input', 'ErrorDescription': '', 'Details': {}}
```

**Comment by Hairo** [comment]
I'm having the same issue.
